import type { EnquiryState } from '../types/enquiry';
import { getProductById } from '../data/products';

const PLY_LABELS: Record<string, string> = {
  '3-ply': '3-ply Corrugated Board',
  '5-ply': '5-ply Corrugated Board',
  '7-ply': '7-ply Corrugated Board',
  'not-sure': 'Not sure — open to recommendation',
};

const PRINTING_LABELS: Record<string, string> = {
  'no-printing': 'No printing required',
  'printing-required': 'Printing required',
  'not-sure': 'Not sure',
};

export function formatEnquiryText(enquiry: EnquiryState): string {
  const { selectedProductIds, specifications, customerDetails } = enquiry;
  const lines: string[] = [];

  lines.push('PACKFORM — PACKAGING ENQUIRY');
  lines.push('='.repeat(60));
  lines.push('');

  lines.push('CUSTOMER DETAILS');
  lines.push('-'.repeat(40));
  lines.push(`Contact Name:   ${customerDetails.contactName ?? '—'}`);
  lines.push(`Company Name:   ${customerDetails.companyName ?? '—'}`);
  lines.push(`Email:          ${customerDetails.email ?? '—'}`);
  lines.push(`Phone:          ${customerDetails.phone ?? '—'}`);
  lines.push(`Delivery City:  ${customerDetails.deliveryCity ?? '—'}`);
  lines.push('');

  lines.push('SELECTED PRODUCTS');
  lines.push('-'.repeat(40));

  selectedProductIds.forEach((productId, index) => {
    const product = getProductById(productId);
    const specs = specifications[productId];
    if (!product || !specs) return;

    lines.push('');
    lines.push(`${index + 1}. ${product.name}`);
    lines.push(`   Category:      ${product.category}`);
    lines.push(`   Quantity:      ${specs.quantity.toLocaleString()} pcs`);

    const hasLength = specs.length && specs.length.trim() !== '';
    const hasWidth = specs.width && specs.width.trim() !== '';
    const hasHeight = specs.height && specs.height.trim() !== '';

    if (hasLength || hasWidth || hasHeight) {
      const l = hasLength ? `${specs.length} mm` : '—';
      const w = hasWidth ? `${specs.width} mm` : '—';
      const h = hasHeight ? `${specs.height} mm` : '—';
      lines.push(`   Dimensions:    L ${l}  ×  W ${w}  ×  H ${h}`);
    } else {
      lines.push('   Dimensions:    Not provided — requirement described in notes');
    }

    lines.push(`   Ply:           ${PLY_LABELS[specs.plyPreference] ?? specs.plyPreference}`);
    lines.push(`   Printing:      ${PRINTING_LABELS[specs.printing] ?? specs.printing}`);

    if (specs.whatWillBePacked && specs.whatWillBePacked.trim() !== '') {
      lines.push(`   What to pack:  ${specs.whatWillBePacked}`);
    }
    if (specs.additionalRequirements && specs.additionalRequirements.trim() !== '') {
      lines.push(`   Notes:         ${specs.additionalRequirements}`);
    }
  });

  lines.push('');
  lines.push('='.repeat(60));
  lines.push('NOTE: This is a demo enquiry generated by Packform.');
  lines.push('This request has NOT been submitted to any system.');
  lines.push('='.repeat(60));

  return lines.join('\n');
}
